### ISSUE TITLE
Add feature to check VTL syntax

### ISSUE THREAD

**Issue by skyler** [purcell/airspeed#26]
I would be handy to have the ability to check the syntax of VTL documents without actually trying to render them. For example, check the syntactical validity of logic in a VTL document without actually executing it. I need to check the syntax of some VTL documents but I do not have data for the variables that the template uses.

**Comment by skyler** [comment]
I just discovered `Template.ensure_compiled()` which seems to provide this functionality. Do you agree?

**Comment by purcell** [comment]
Yes, that should do the trick, I think.
