### ISSUE TITLE
Remove dev suffix from release versions

### ISSUE THREAD

**Issue by tuukkamustonen** [purcell/airspeed#30]
As can be seen in [PyPI release history](https://pypi.org/project/airspeed/#history), all releases look like _developmental releases_ (see https://www.python.org/dev/peps/pep-0440/#developmental-releases) but they are actually standard releases.

So, developmental releases require (`pip`) `--pre` to install, but `airspeed` releases install without it.

It's just a bit confusing :)

(P.S. How mature/stable/reliable do you think the library is? Is it used in production somewhere? The version numbers just give impression that it might not be the case?).

**Comment by purcell** [comment]
Thanks - done in b015d54, and a non-dev package has been uploaded to PyPI. The library is pretty mature, and I suspect it's in production here and there, but I'm not actually sure. For my part, I don't really work with Python any more, but I try to keep this library well-maintained and respond to pull requests.

**Comment by tuukkamustonen** [comment]
Thanks! Good to hear it's mature - we're planning to use it, too. Velocity may not be on the bleeding edge but there's legacy code that we need to maintain...

Just one thing: Looks like you accidentally uploaded a macOS-specific package:

![image](https://user-images.githubusercontent.com/94327/41823268-f7600d24-7805-11e8-8cd4-a72d84d3f82d.png)

I would suggest you bump the version, too. Not sure if pip will really resolve `0.5.9` over the existing `0.5.9.dev20180330`(?)
