### ISSUE TITLE
Prefer dict items over built-in methods

### ISSUE THREAD

**Issue by trilliput** [purcell/airspeed#32]
Currently it's not possible to use keys like 'items' in dictionaries (maps), because it has a method `items`. I'd suggest to prefer dictionary items over methods in case they collide.

**Comment by purcell** [comment]
Yep, that would probably make sense. Would you mind writing a quick test case and I'll see if I can fix it when time allows?

**Comment by purcell** [comment]
LOL, ignore me -- just saw your PR #33 now. :-)

**Comment by purcell** [comment]
LOL, ignore me -- just saw your PR #33 now. :-)
