### ISSUE TITLE
Untagged release on GitHub.

### ISSUE THREAD

**Issue by Aniket-Pradhan** [purcell/airspeed#36]
Hey!

I was going through airspeed, and I noticed that [PyPI](https://pypi.org/project/airspeed/) contains the package with the release `0.5.12`, and the latest release on Github is `0.5.11`. 

Probably you forgot to tag the same release here, I guess.

**Comment by Aniket-Pradhan** [comment]
Also, to note, the license file is missing from the PyPI release tar.

**Comment by purcell** [comment]
Thanks, yes, forgot that. Release should be there now.

**Comment by purcell** [comment]
Thanks, yes, forgot that. Release should be there now.
