### ISSUE TITLE
Variables - Alternate value

### ISSUE THREAD

**Issue by pmotyka** [purcell/airspeed#43]
I've tried using the "Alternate value" variable technique and it doesn't seem to be supported by Airspeed.  Can someone confirm this is the case?

http://velocity.apache.org/engine/devel/vtl-reference.html#variables

`expected } in formal reference, got: |`

Thanks!

**Comment by purcell** [comment]
Published as 0.5.15.

**Comment by pmotyka** [comment]
Thank you!
