### ISSUE TITLE
Deprecation warning due to invalid escape sequences.

### ISSUE THREAD

**Issue by tirkarthi** [purcell/airspeed#44]
Deprecation warning due to invalid escape sequences. Using raw strings or escaping them again helps in resolving this. Check https://github.com/asottile/pyupgrade/ for automatic fix of this.

```
find . -iname '*.py' | grep -Ev 'rdf4|doc|benchmark|tool' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./airspeed/__init__.py:628: DeprecationWarning: invalid escape sequence \.
  DOT = re.compile('\.(.*)', re.S)
./airspeed/__init__.py:753: DeprecationWarning: invalid escape sequence \*
  '#(?:#.*?(?:\n|$)|\*.*?\*#(?:[ \t]*\n)?)(.*)$',
```

**Comment by purcell** [comment]
Thanks for the heads-up. Want to submit a fix?

**Comment by purcell** [comment]
(Or is it only those 2 occurrences?)

**Comment by tirkarthi** [comment]
Sure, yes only 2 occurrences. I have created #46 .
