### ISSUE TITLE
Support #define directive block

### ISSUE THREAD

**Issue by calvernaz** [purcell/airspeed#55]
Hi @purcell, I'm having issues handling the `#define` directive (example below), and wondering if it's in your plans to support it?

```
import airspeed

def test_templating():
    template = """
  #define( $loop )
  #end
 """
    t = airspeed.Template(template)
    replaced = t.merge(locals())

if __name__ == "__main__":
    test_templating()
```
 Currently it raises this exception `airspeed.TemplateSyntaxError: line 5, column 3: expected block element in template body, got: #end` and navigating the code I couldn't figure a handler for it

**Comment by purcell** [comment]
Hi! I haven't used `#define` but it might be easy to add it. Could you perhaps provide a couple of example unit tests? In particular, I can't tell from the [user guide](https://velocity.apache.org/engine/1.7/user-guide.html) whether the result of a `#define` block is computed only once, or each time it is dereferenced using its name (e.g. `$loop` in your example).

**Comment by calvernaz** [comment]
Absolutely, I have an example below on how it can be used! If you need anything else to test it, happy to do it

```
#set( $body = $input.json("$") )

#define( $loop )
{
    #foreach($key in $map.keySet())
        #set( $k = $util.escapeJavaScript($key) )
        #set( $v = $util.escapeJavaScript($map.get($key)).replaceAll("\\'", "'") )
        "$k": "$v"
        #if( $foreach.hasNext ) , #end
    #end
}
#end

  {
    #set( $map = $context.authorizer )
    "enhancedAuthContext": $loop,

    #set( $map = $input.params().header )
    "headers": $loop,

    #set( $map = $input.params().querystring )
    "query": $loop,

    #set( $map = $input.params().path )
    "path": $loop,

    #set( $map = $context.identity )
    "identity": $loop,

    #set( $map = $stageVariables )
    "stageVariables": $loop,
}

```

**Comment by purcell** [comment]
Thanks. Yeah, this is going to be quite involved to implement. Since I don't use Airspeed very actively myself, I'm going to struggle to find time to implement it. The necessary machinery is there in the code, but this involves introducing a different type of variable as well as parsing the `#define` construct itself (probably based on the `#macro` code). In the meantime, I wonder if using `#macro` is a viable alternative, it seems much cleaner anyway: instead of
```
 #set( $map = $input.params().path )
 "path": $loop,
```
you might have
```
 "path": #my_loop( $input.params().path ),
```

**Comment by calvernaz** [comment]
Thanks for coming back, and I understand that this requires some effort from your side. I'll try the macro alternative, thanks!

**Comment by purcell** [comment]
Done in #57

**Comment by calvernaz** [comment]
> Done in #57

Thanks @purcell
