### ISSUE TITLE
replace nose testing framework

### ISSUE THREAD

**Issue by fmoessbauer** [purcell/airspeed#59]
Hi,

I'm a maintainer of the Debian packaging of the airspeed project.

The airspeed project internally uses the nose testing framework, which is not maintained since 2015.
Are there plans to replace that framework?

For details, see:

- https://github.com/nose-devs/nose/commit/0f40fa995384afad
- https://pypi.org/project/nose/#history
- https://groups.google.com/g/linux.debian.bugs.dist/c/Y9pjJr9gIn0

**Comment by purcell** [comment]
There are no plans, but I'm open to it. The tests are just unittest.py tests anyway (which framework I originally wrote 20+ years ago!).

**Comment by purcell** [comment]
Also worth noting that `nose` is only included in `tests_require`, not `install_requires`. I'm surprised if the dev dependencies get included in the Debian package.

**Comment by purcell** [comment]
I made a corresponding change, if you'd like to check it out. Presumably it would need to be released to be useful to you?

**Comment by fmoessbauer** [comment]
Thanks for the immediate response. That was quick!

> Also worth noting that nose is only included in tests_require, not install_requires. I'm surprised if the dev dependencies get included in the Debian package.

The "binary package" of course does not depend on the -dev dependencies. But the "source package" (which is used to generate the binary package) depends on the -dev deps, as well as the testing dependencies. By that, we can run the tests at build time and detect issues early. If you are interested in the details, have a look at [1].

> I made a corresponding change, if you'd like to check it out. Presumably it would need to be released to be useful to you?

The patch looks good. I'll give it a try tomorrow and report back. Then we would need a release to fix the issue on our side.
BTW: you removed the coverage dep as well.

- [1] https://salsa.debian.org/python-team/packages/python-airspeed/-/blob/main/debian/control#L12

**Comment by fmoessbauer** [comment]
I can confirm that this works. Could you please cut a new (patch) release?

**Comment by purcell** [comment]
> BTW: you removed the coverage dep as well.

Yeah, that's fine — folks can add it in and incorporate it via tox or manual installation if they like. It might get added back in later if I decide to add proper CI here.

> Could you please cut a new (patch) release?

Done: 0.5.20.

**Comment by fmoessbauer** [comment]
The new release is now uploaded to and accepted in Debian unstable. Thanks!
